# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2e778f4b468f8f0079399fef4dbe820228e47903bd16edaa0dfe24f7d585faf1715c0d4b24d8763a568f06ea9136713075587c0e5f35561638c00b987ebc244

test:
  secret_key_base: 029626989f8ca85705f03edda300e45550029b0bfe1d5c0a049f169aecc62ce93e6b7d07ec18b674d6fbeb05ec5807e4ca3cbd934a37e81cc15e3bab33b80c1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
